Points 16-20
noblica/javascript pull request #8
Opened 2016-12-23 14:05 UTC by noblica

Please go through this, once you've gone through the "points-12-16" PR.

2017-01-18 08:32 UTC, canthugeverycat requested changes

2017-01-18 08:32 UTC, canthugeverycat commented on README.md
> +
**Edit (Deckey):** I disagree with the disagreement. The code is syntactically cleaner but the functionality of placing breakpoints through each variable declaration is not possible using this syntax. This might not be relevant when the declarations are primitives but it is a factor when it comes to declarations that contain references/calculations.
Declaration-by-declaration breakpointing can be useful in the following example:
Also, the previous disagreer is butt-ugly.

```javascript
	const items = getItems(),
              d = new Date(),
	      goSportsTeam = items.length + d.getTime(),
	      dragonball = items[items.length - 1] + goSportsTeam;
```

2017-01-19 08:42 UTC, noblica commented on README.md
> +
Good point. Agreed, I'll add this as an example. Thanks!

2017-01-23 10:04 UTC, AleksandarBacaninSoprex approved these changes

2017-01-23 23:06 UTC, merged